### ISSUE TITLE
kubernetes or microk8s ?

### ISSUE THREAD

**Issue by bencz** [sebastianczech/k8s-oci#2]
This script, creates a k8s cluster using the kubernetes or using microk8s ?

**Comment by sebastianczech** [comment]
hi, the code is preparing infrastructure using Terraform and configuration is being made using Ansible. Regarding k8s cluster - I was using `microk8s`: https://github.com/sebastianczech/k8s-oci/blob/3d513107103b0a593c004a9fe6623e4f7b7ee11d/conf/conf-k8s-oracle-cloud/tasks/install.yml#L9-L13

**Comment by bencz** [comment]
Thanks!!
Time to try 👍
